In [30]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import boxcox
pd.set_option('display.max_columns', None)
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
from sklearn.model_selection import train_test_split,cross_val_score, KFold,GridSearchCV,StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,make_scorer

In [31]:
df = pd.read_csv('Breast_Cancer.csv')
df['Status'] = df['Status'].map({'Alive': 0, 'Dead': 1})
df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,0
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,0
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,0
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,0
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,0

In [32]:
df = pd.get_dummies(df, columns=['Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage', 
                                             'differentiate', 'A Stage', 'Estrogen Status', 
                                             'Progesterone Status', 'Grade'], drop_first=True)
df.head()

,Age,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months,Status,Race_Other,Race_White,Marital Status_Married,Marital Status_Separated,Marital Status_Single,Marital Status_Widowed,T Stage _T2,T Stage _T3,T Stage _T4,N Stage_N2,N Stage_N3,6th Stage_IIB,6th Stage_IIIA,6th Stage_IIIB,6th Stage_IIIC,differentiate_Poorly differentiated,differentiate_Undifferentiated,differentiate_Well differentiated,A Stage_Regional,Estrogen Status_Positive,Progesterone Status_Positive,Grade_1,Grade_2,Grade_3
0,68,4,24,1,60,0,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,True
1,50,35,14,5,62,0,False,True,True,False,False,False,True,False,False,True,False,False,True,False,False,False,False,False,True,True,True,False,True,False
2,58,63,14,7,75,0,False,True,False,False,False,False,False,True,False,False,True,False,False,False,True,False,False,False,True,True,True,False,True,False
3,58,18,2,1,84,0,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,True
4,47,41,3,1,50,0,False,True,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,False,True,True,True,False,False,True

In [33]:
X = df.drop('Status', axis = 1)
y = df['Status']
model = LogisticRegression(max_iter=10000)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [34]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.91      0.98      0.95       682
           1       0.84      0.46      0.59       123

    accuracy                           0.90       805
   macro avg       0.87      0.72      0.77       805
weighted avg       0.90      0.90      0.89       805

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, f1_score

In [36]:
accuracy_score(y_test, predictions)

0.9031055900621118

In [37]:
confusion_matrix(y_test, predictions)

array([[671,  11],
       [ 67,  56]])

In [38]:
roc_auc_score(y_test, predictions)

np.float64(0.719577760293732)

In [39]:
f1_score(y_test, predictions, average='macro')

np.float64(0.7672720533728687)

In [41]:
precision_score(y_test, predictions, average = 'macro')

np.float64(0.8725174938316547)